name: Build
on:
  push:
    branches: [main, proposed]
  pull_request:
  schedule:
    # 16:38 UTC on Tuesdays
    - cron: "38 16 * * TUE"
  repository_dispatch:
    types: [tests]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build with Emscripten
        run: |
          cd sc2
          docker build --tag=uqm-wasm -f wasm/Dockerfile .
      - name: Compare detected configuration
        run: |
          cd sc2
          docker run --rm uqm-wasm grep CHOICE config.state \
            |diff -us --color=always wasm/config.state.expected -
